config/routes.rb
Rails.application.routes.draw do
  
  
  resources :users
  resources :applicants
  get 'routing/show'

  resources :games
  get 'models_need_dots/show'

  resources :students
  get 'welcome/index'

  

  root 'welcome#index'

end

app/models/student.rb
class Student < ActiveRecord::Base
  validates :first_name, presence: true
  validates :major, presence: true
end

app/controllers/students_controller.rb
class StudentsController < ApplicationController
  before_action :set_student, only: [:show, :edit, :update, :destroy]
  # GET /students
  # GET /students.json
  def index
    @students = Student.all
    respond_to do |format|
      format.html { 
          @students_json = @students.map{ |s| StudentSerializer.new(s).serializable_hash }
          @urls = {
            students: students_path
          }
      }
      format.json { render json: @students }
    end
  end

  # GET /students/1
  # GET /students/1.json
  def show
  end

  # GET /students/new
  def new
    @student = Student.new
  end

  # GET /students/1/edit
  def edit
  end

  # POST /students
  # POST /students.json
  def create
    @student = Student.new(student_params)

    respond_to do |format|
      if @student.save
        format.html { redirect_to @student, notice: 'Student was successfully created.' }
        format.json { render :show, status: :created, location: @student }
      else
        format.html { render :new }
        format.json { render json: @student.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /students/1
  # PATCH/PUT /students/1.json
  def update
    respond_to do |format|
      if @student.update(student_params)
        format.html { redirect_to @student, notice: 'Student was successfully updated.' }
        format.json { render :show, status: :ok, location: @student }
      else
        format.html { render :edit }
        format.json { render json: @student.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /students/1
  # DELETE /students/1.json
  def destroy
    @student.destroy
    respond_to do |format|
      format.html { redirect_to students_url, notice: 'Student was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_student
      @student = Student.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def student_params
      params.require(:student).permit(:first_name, :last_name, :level, :major, :joining_semester)
    end
end

app/helpers/students_helper.rb
module StudentsHelper
end

app/views/students/_form.html.erb
<div ng-app="UlResourceHub">
  <%= form_for @student, id: "studentForm", html: {name: "studentForm", "novalidate" => true} do |f| %>
    <% if @student.errors.any? %>
      <div id="error_explanation">
        <h2><%= pluralize(@student.errors.count, "error") %> prohibited this student from being saved:</h2>

        <ul>
        <% @student.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
        </ul>
      </div>
    <% end %>

    <div class="form-group" ng-class="{ 'has-error': studentForm['student[first_name]'].$invalid}">
      <%= f.label :first_name %><br>
      <%= f.text_field :first_name, class: "form-control", "ng-model" => "first_name", required: true %>
      <span class="help-block" ng-show="studentFrom['student[first_name]'].$error.required"> Required </span>
    </div>
    <div class="form-group">
      <%= f.label :last_name %><br>
      <%= f.text_field :last_name %>
    </div>
    <div class="form-group">
      <%= f.label :level %><br>
      <%= f.text_field :level %>
    </div>
    <div class="form-group">
      <%= f.label :major %><br>
      <%= f.text_field :major %>
    </div>
    <div class="form-group">
      <%= f.label :joining_semester %><br>
      <%= f.text_field :joining_semester %>
    </div>
    <%= f.submit "Save", class: "btn btn-primary", "ng-disabled" => "studentForm.$invalid"%>
  <% end %>
</div>  

app/views/students/edit.html.erb
<h1>Editing Student</h1>

<%= render 'form' %>

<%= link_to 'Show', @student %> |
<%= link_to 'Back', students_path %>

app/views/students/index.html.erb
<div ng-app="UlResourceHub" ng-controller="StudentsController" ng-init="urls=<%=@urls.to_json %>;getStudents()">
  <div class="row">
      <p id="notice"><%= notice %></p>
      <h3>Listing Students</h3>
          <div class="col s2">First name</div>
          <div class="col s2">Last name</div>
          <div class="col s2">Level</div>
          <div class="col s2">Major</div>
          <div class="col s2">Joining semester</div>
          <th colspan="3"></th>
  </div>        
  <div ng-repeat="student in students" class="row">
          <div class="col s2">  {{student.first_name }} </div>
          <div class="col s2">  {{ student.last_name }} </div>
          <div class="col s2">  {{ student.level }} </div>
          <div class="col s2">  {{ student.major }}</div>
          <div class="col s2">  {{ student.joining_semester }}</div>
  </div>
<br>
<%= link_to 'New Student', new_student_path %>

<div class="row">
  <div class="col s6">
    <form ng-submit="save()"> 
      <div class="form-group">
        <label>First Name</label>
        <input type="text" class="form-control" ng-model="student.first_name" /> 
      </div>
      <div class="form-group">
        <label>Last Name</label>
        <input type="text" class="form-control" ng-model="student.last_name" /> 
      </div>
      <div class="form-group">
        <label>Major</label>
        <input type="text" class="form-control" ng-model="student.major" /> 
      </div>
      <div class="form-group">
        <label>Level</label>
        <input type="text" class="form-control" ng-model="student.level" />
      </div>
        <button type="button" class="btn btn-primary" ng-click="">
          Save
        </button>
    </form>
  </div>
</div>  
</div>

app/views/students/new.html.erb
<h1>New Student</h1>

<%= render 'form' %>

<%= link_to 'Back', students_path %>

app/views/students/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>First name:</strong>
  <%= @student.first_name %>
</p>

<p>
  <strong>Last name:</strong>
  <%= @student.last_name %>
</p>

<p>
  <strong>Level:</strong>
  <%= @student.level %>
</p>

<p>
  <strong>Major:</strong>
  <%= @student.major %>
</p>

<p>
  <strong>Joining semester:</strong>
  <%= @student.joining_semester %>
</p>

<%= link_to 'Edit', edit_student_path(@student) %> |
<%= link_to 'Back', students_path %>