config/routes.rb
Rails.application.routes.draw do
  
  
  resources :users
  resources :applicants
  get 'routing/show'

  resources :games
  get 'models_need_dots/show'

  resources :students
  get 'welcome/index'

  

  root 'welcome#index'

end

app/models/applicant.rb
class Applicant < ActiveRecord::Base
end

app/controllers/applicants_controller.rb
class ApplicantsController < ApplicationController
  before_action :set_applicant, only: [:show, :edit, :update, :destroy]

  # GET /applicants
  # GET /applicants.json
  def index
    @applicants = Applicant.all
  end

  # GET /applicants/1
  # GET /applicants/1.json
  def show
  end

  # GET /applicants/new
  def new
    @applicant = Applicant.new
  end

  # GET /applicants/1/edit
  def edit
  end

  # POST /applicants
  # POST /applicants.json
  def create
    @applicant = Applicant.new(applicant_params)

    respond_to do |format|
      if @applicant.save
        format.html { redirect_to @applicant, notice: 'Applicant was successfully created.' }
        format.json { render :show, status: :created, location: @applicant }
      else
        format.html { render :new }
        format.json { render json: @applicant.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /applicants/1
  # PATCH/PUT /applicants/1.json
  def update
    respond_to do |format|
      if @applicant.update(applicant_params)
        format.html { redirect_to @applicant, notice: 'Applicant was successfully updated.' }
        format.json { render :show, status: :ok, location: @applicant }
      else
        format.html { render :edit }
        format.json { render json: @applicant.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /applicants/1
  # DELETE /applicants/1.json
  def destroy
    @applicant.destroy
    respond_to do |format|
      format.html { redirect_to applicants_url, notice: 'Applicant was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_applicant
      @applicant = Applicant.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def applicant_params
      params.require(:applicant).permit(:first_name, :last_name, :clid, :email, :major, :joining_semester, :degree, :date_of_birth, :phone, :address1, :address2, :city, :state, :country, :zipcode)
    end
end

app/views/applicants/_form.html.erb
<%= form_for(@applicant) do |f| %>
  <% if @applicant.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@applicant.errors.count, "error") %> prohibited this applicant from being saved:</h2>

      <ul>
      <% @applicant.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :first_name %><br>
    <%= f.text_field :first_name %>
  </div>
  <div class="field">
    <%= f.label :last_name %><br>
    <%= f.text_field :last_name %>
  </div>
  <div class="field">
    <%= f.label :clid %><br>
    <%= f.text_field :clid %>
  </div>
  <div class="field">
    <%= f.label :email %><br>
    <%= f.text_field :email %>
  </div>
  <div class="field">
    <%= f.label :major %><br>
    <%= f.text_field :major %>
  </div>
  <div class="field">
    <%= f.label :joining_semester %><br>
    <%= f.text_field :joining_semester %>
  </div>
  <div class="field">
    <%= f.label :degree %><br>
    <%= f.text_field :degree %>
  </div>
  <div class="field">
    <%= f.label :date_of_birth %><br>
    <%= f.text_field :date_of_birth %>
  </div>
  <div class="field">
    <%= f.label :phone %><br>
    <%= f.text_field :phone %>
  </div>
  <div class="field">
    <%= f.label :address1 %><br>
    <%= f.text_area :address1 %>
  </div>
  <div class="field">
    <%= f.label :address2 %><br>
    <%= f.text_field :address2 %>
  </div>
  <div class="field">
    <%= f.label :city %><br>
    <%= f.text_field :city %>
  </div>
  <div class="field">
    <%= f.label :state %><br>
    <%= f.text_field :state %>
  </div>
  <div class="field">
    <%= f.label :country %><br>
    <%= f.text_field :country %>
  </div>
  <div class="field">
    <%= f.label :zipcode %><br>
    <%= f.text_field :zipcode %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/applicants/edit.html.erb
<h1>Editing Applicant</h1>

<%= render 'form' %>

<%= link_to 'Show', @applicant %> |
<%= link_to 'Back', applicants_path %>

app/views/applicants/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Applicants</h1>

<table>
  <thead>
    <tr>
      <th>First name</th>
      <th>Last name</th>
      <th>Clid</th>
      <th>Email</th>
      <th>Major</th>
      <th>Joining semester</th>
      <th>Degree</th>
      <th>Date of birth</th>
      <th>Phone</th>
      <th>Address1</th>
      <th>Address2</th>
      <th>City</th>
      <th>State</th>
      <th>Country</th>
      <th>Zipcode</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @applicants.each do |applicant| %>
      <tr>
        <td><%= applicant.first_name %></td>
        <td><%= applicant.last_name %></td>
        <td><%= applicant.clid %></td>
        <td><%= applicant.email %></td>
        <td><%= applicant.major %></td>
        <td><%= applicant.joining_semester %></td>
        <td><%= applicant.degree %></td>
        <td><%= applicant.date_of_birth %></td>
        <td><%= applicant.phone %></td>
        <td><%= applicant.address1 %></td>
        <td><%= applicant.address2 %></td>
        <td><%= applicant.city %></td>
        <td><%= applicant.state %></td>
        <td><%= applicant.country %></td>
        <td><%= applicant.zipcode %></td>
        <td><%= link_to 'Show', applicant %></td>
        <td><%= link_to 'Edit', edit_applicant_path(applicant) %></td>
        <td><%= link_to 'Destroy', applicant, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Applicant', new_applicant_path %>

app/views/applicants/new.html.erb
<h1>New Applicant</h1>

<%= render 'form' %>

<%= link_to 'Back', applicants_path %>

app/views/applicants/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>First name:</strong>
  <%= @applicant.first_name %>
</p>

<p>
  <strong>Last name:</strong>
  <%= @applicant.last_name %>
</p>

<p>
  <strong>Clid:</strong>
  <%= @applicant.clid %>
</p>

<p>
  <strong>Email:</strong>
  <%= @applicant.email %>
</p>

<p>
  <strong>Major:</strong>
  <%= @applicant.major %>
</p>

<p>
  <strong>Joining semester:</strong>
  <%= @applicant.joining_semester %>
</p>

<p>
  <strong>Degree:</strong>
  <%= @applicant.degree %>
</p>

<p>
  <strong>Date of birth:</strong>
  <%= @applicant.date_of_birth %>
</p>

<p>
  <strong>Phone:</strong>
  <%= @applicant.phone %>
</p>

<p>
  <strong>Address1:</strong>
  <%= @applicant.address1 %>
</p>

<p>
  <strong>Address2:</strong>
  <%= @applicant.address2 %>
</p>

<p>
  <strong>City:</strong>
  <%= @applicant.city %>
</p>

<p>
  <strong>State:</strong>
  <%= @applicant.state %>
</p>

<p>
  <strong>Country:</strong>
  <%= @applicant.country %>
</p>

<p>
  <strong>Zipcode:</strong>
  <%= @applicant.zipcode %>
</p>

<%= link_to 'Edit', edit_applicant_path(@applicant) %> |
<%= link_to 'Back', applicants_path %>